# Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# Force use of the bug-report / feature-request templates; no free-form issues.
blank_issues_enabled: false
